#
# Url
#

# don't end with "/"
url: http://ttskch.github.io
baseurl: ""
# url: http://localhost:4000
# baseurl: ""
permalink: pretty

#
# Basics
#

title: "Takashi Kanemoto aka ttskch"
description: Takashi Kanemoto's portfolio
avatar: //avatars.githubusercontent.com/ttskch
# favicon: /favicon.ico
favicon: //avatars.githubusercontent.com/ttskch
language: ja
# language: en
google_analytics: UA-28477336-5 # e.g. UA-000000-01

#
# Links
#

links:
  - url: https://twitter.com/ttskch
    icon: fa-twitter
    label: Twitter
  - url: https://www.facebook.com/ttskch
    icon: fa-facebook
    label: Facebook
  - url: https://github.com/ttskch
    icon: fa-github
    label: GitHub
  - url: https://note.mu/ttskch
    icon: fa-sticky-note-o fa-rotate-180
    label: Blog
  - url: http://tech.quartetcom.co.jp
    icon: fa-code
    label: Tech Blog
  - url: https://qiita.com/ttskch
    icon: fa-smile-o
    label: Qiita
  - url: https://speakerdeck.com/ttskch
    icon: fa-picture-o
    label: Speaker Deck
  - url: https://www.linkedin.com/in/ttskch
    icon: fa-linkedin
    label: LinkedIn
  - url: https://www.instagram.com/ttskch
    icon: fa-instagram
    label: Instagram
  - url: https://booklog.jp/users/ttskch
    icon: fa-book
    label: Booklog
  - url: http://pocitta.jp/ttskch
    icon: fa-gift
    label: pocitta
  - url: https://www.amazon.co.jp/registry/wishlist/O4B5ZRU2EXQV
    icon: fa-amazon
    label: Wishlist
  - url: mailto:ttskch@gmail.com
    icon: fa-envelope-o
    label: Email

#
# SEO
# @see https://github.com/jekyll/jekyll-seo-tag
#

logo: https://avatars.githubusercontent.com/ttskch
lang: ja_JP
twitter:
  username: ttskch
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/ttskch

#
# Other
#

markdown: kramdown
kramdown:
  input: GFM

# @see https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from

timezone: Asia/Tokyo
encoding: utf-8

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

include:
  - "_pages"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - LICENSE
  - README.md
  - _posts/drafts
